global_variables:
  - &spark_master_ip_address 188.184.104.25
  - &spark_master_fqdn simple-lc01.cern.ch
  - &spark_worker_ip_address 188.184.30.19
  - &spark_worker_fqdn simple-lc02.cern.ch
  - &spark_submit_ip_address 188.185.84.189
  - &spark_submit_fqdn simple-lc03.cern.ch

spark_master_runtime_variables:
  - &spark_master_runtime_var_host 
    __from__: *spark_master_fqdn

spark_worker_runtime_variables:
  - &spark_worker_runtime_var_host 
    __from__: *spark_worker_fqdn
  - &spark_worker_runtime_var_spark_master 
    __from__: *spark_master_fqdn

spark_submit_runtime_variables:
  - &spark_submit_runtime_var_spark_master 
    __from__: *spark_submit_fqdn

preferred_tech_stack:
  level_1_configuration: puppet
  level_2_configuration: sh
  container_orchestration: docker-swarm
  container: docker

site_infrastructure:
  - fqdn: *spark_master_fqdn
    ip_address: *spark_master_ip_address
  - fqdn: *spark_worker_fqdn
    ip_address: *spark_worker_ip_address
  - fqdn: *spark_submit_fqdn
    ip_address: *spark_submit_ip_address

lightweight_components:
  - type: spark_master
    name: spark-master
    repository_url: "https://github.com/maany/spark_master"
    repository_revision: "master"
    execution_id: 0
    deploy:
      - node: *spark_master_fqdn
        container_count: 1
    config:
        enable_init_daemon: false
    supplemental_config:
        "spark-defaults.conf":
          - "spark.memory.fraction 0.75"
          - "spark.executor.memory 1g"
          - "spark.driver.cores 1"

  - name: spark-worker
    type: spark_worker
    repository_url: "https://github.com/maany/spark_worker"
    repository_revision: "master"
    execution_id: 1
    deploy:
      - node: *spark_worker_fqdn
        container_count: 1
    config:
        enable_init_daemon: false
        spark_master: *spark_master_fqdn
    supplemental_config:

  - name: spark-submit
    type: spark_submit
    repository_url: "https://github.com/maany/spark_submit"
    repository_revision: "master"
    execution_id: 2
    deploy:
      - node: *spark_submit_fqdn
        container_count: 1
    config:
        enable_init_daemon: false
