vars:
  - &spark_master_ip_address 188.184.104.25
  - &spark_worker_ip_address 188.184.30.19
  - &spark_submit_ip_address 188.185.30.19

spark_master_runtime_variables:
  - &master_runtime_var_host simple-lc01.cern.ch

spark_worker_runtime_variables:
  - &worker_runtime_var_host simple-lc02.cern.ch

spark_submit_runtime_variables:
  - &submit_runtime_var_host simple-lc02.cern.ch

preferred_tech_stack:
  level_1_configuration: puppet
  level_2_configuration: sh
  container_orchestration: docker-swarm
  container: docker

site_infrastructure:
  - fqdn: spark-master.cern.ch
    ip_address: *spark_master_ip_address
  - fqdn: spark-worker.cern.ch
    ip_address: *spark_worker_ip_address
  - fqdn: spark-submit.cern.ch
    ip_address: *spark_submit_ip_address

lightweight_components:
  - type: spark_master
    name: spark-master
    repository_url: "https://github.com/JuliaGavrilenko/spark_master"
    repository_revision: "master"
    execution_id: 0
    deploy:
      - node: spark-master.cern.ch
        container_count: 1
    config:
        host: *master_runtime_var_host
        enable_init_daemon: false
    supplemental_config:
        "spark-defaults.conf":
          - "spark.memory.fraction 0.75"
          - "spark.executor.memory 1g"
          - "spark.driver.cores 1"

  - name: spark-worker
    type: spark_worker
    repository_url: "https://github.com/JuliaGavrilenko/spark_worker"
    repository_revision: "master"
    execution_id: 1
    deploy:
      - node: spark-worker.cern.ch
        container_count: 1
    config:
        host: *worker_runtime_var_host
        enable_init_daemon: false
        SPARK_MASTER: spark://spark-master.cern.ch:7077
    supplemental_config:
      "spark-defaults.conf":
        - "spark.memory.fraction 0.75"
        - "spark.executor.memory 1g"
        - "spark.driver.cores 1"

  - name: spark-submit
    type: spark_submit
    repository_url: "https://github.com/JuliaGavrilenko/spark_submit"
    repository_revision: "master"
    execution_id: 2
    deploy:
      - node: spark-submit.cern.ch
        container_count: 1
    config:
        spark_master: *submit_runtime_var_host
        enable_init_daemon: false
        SPARK_MASTER: spark://spark-master.cern.ch:7077
    supplemental_config:
      "spark-defaults.conf":
        - "spark.memory.fraction 0.75"
        - "spark.executor.memory 1g"
        - "spark.driver.cores 1"
